### ISSUE TITLE
opencv2 dependency not working on indigo

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_apps#112]
we cannot release this on indigo yet as the `opencv2` dependency cannot be resolved. Please read http://wiki.ros.org/indigo/Migration#OpenCV and fix (by creating an `indigo-devel` branch I suppose).

**Comment by marc-hanheide** [comment]
sorry, no extra branch needed, just depend on `cv_bridge` as it says in the guide.

**Comment by cdondrup** [comment]
Will try

**Comment by cdondrup** [comment]
@marc-hanheide, did that work? Can't really find where Jenkins is building the indigo jobs.

**Comment by marc-hanheide** [comment]
https://lcas.lincoln.ac.uk/jenkins/job/devel-indigo-scitos_apps/ ?

**Comment by cdondrup** [comment]
Ah, OK. Thought there was a release job for that as well. But since that reposted success, I'll close this issue.

**Comment by marc-hanheide** [comment]
I was about to setup a release job, but then it failed to do that because of the missing dependency

**Comment by cdondrup** [comment]
Fair enough. Please just open another issue or re-open this one if something else fails.

**Comment by marc-hanheide** [comment]
we'll see soon

**Comment by marc-hanheide** [comment]
https://github.com/strands-project/rosdistro/pull/66

**Comment by marc-hanheide** [comment]
success!

**Comment by cdondrup** [comment]
Almost too easy.
