### ISSUE TITLE
[scitos_docking] How to configure injected pose

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_apps#128]
How do we configure the pose which is injected after successful docking? We have a map which we wish to reuse but with the docking station not at the origin.

**Comment by hawesie** [comment]
@gestom any news on this?

**Comment by gestom** [comment]
Should be solved now. To determine the position of the charging station in the map, dock to it (automatically) and ask for the /robot_pose. Note that the station and robot orietation oppose each other.

**Comment by hawesie** [comment]
> Note that the station and robot orietation oppose each other.

Does that mean the orientation from `/robot_pose` should be rotated 180 before being used for the parameter for the station?

**Comment by gestom** [comment]
yeap, exactly, stationPhi = robot_pose.yaw+\pi

**Comment by marc-hanheide** [comment]
it's now released, so I close this.
