### ISSUE TITLE
Segment detection during calibration 

### ISSUE THREAD

**Issue by kunzel** [strands-project/scitos_apps#16]
@gestom , I enabled the debug flag in the CCircleDetect.cpp. Can you see anything in this output (https://gist.github.com/kunzel/6120375) that gives me a clue whether the circles are detected or not?

Btw the /charging/processedimage looks pretty corrupted. The format of the Image from MORSE is like this:
[..] 
The data captured by the camera, stored as a Python Buffer \
            class  object. The data is of size `(cam_width * cam_height * 4)`\
            bytes. The image is stored as RGBA.")
[..]
Does this look OK for you?

thanks!

**Comment by gestom** [comment]
Hi Lars, 

the problem is that detection is expecting the image to be in RGB format with size cam_width_cam_height_3.

Tom

**Comment by gestom** [comment]
If the image gets segmented OK, you should get something like this: 
![robotstation](https://f.cloud.github.com/assets/4293593/884954/b7de608a-f9c3-11e2-80db-34f6652ea326.jpg)
I will improve the code to take into account the RGBA image format.

Tom

**Comment by gestom** [comment]
I have modified the image processing to work on monochromatic image and the success of the docking is evaluated based on the battery_state topic now.

Therefore, the docking should be compatible with simulation.

**Comment by kunzel** [comment]
Great, thanks. I was just able to switch the image provided by the simulation from RGBA to RGB. A color image should in principle be fine.
