### ISSUE TITLE
docking does not build because of missing action header

### ISSUE THREAD

**Issue by cdondrup** [strands-project/scitos_apps#21]
I just updated and when trying to build I get:

```
scitos_apps/scitos_docking/src/dockingClient.cpp:2:45: fatal error: scitos_apps_msgs/ChargingAction.h: No such file or directory
compilation terminated.
```

and

```
In file included from scitos_apps/scitos_docking/src/CChargingClient.cpp:1:0:
scitos_apps/scitos_docking/src/CChargingClient.h:11:45: fatal error: scitos_apps_msgs/ChargingAction.h: No such file or directory
compilation terminated.
```

So it seems that the message headers are not generated before trying to build the lib and binary mentioned. This would not surprise me in the case of CChargingClient because it does not define the dependencies the right way. But I don't really get the first error, because the definitions in the CMakeLists.txt seem to be right:

```
add_executable(visual_charging_client src/dockingClient.cpp)
add_dependencies(visual_charging_client scitos_msgs_gencpp scitos_apps_msgs_genccp actionlib)
```

Still it does not seem to care whether the headers are generated or not. Do you need to do something else to make it work with actionlib? Google couldn't answer my question so maybe someone here does know why this fails.

**Comment by gestom** [comment]
Resolved by updating CMakeLists

**Comment by cdondrup** [comment]
You're right. 2204a03cbfd1d642e12a8e7b801a446ae69b432e seems to fix the problem. Works fine for me now.
