### ISSUE TITLE
Visual docking dependencies not agreeing with ros

### ISSUE THREAD

**Issue by nilsbore** [strands-project/scitos_apps#30]
We're trying to get the visual docking working but are getting some problems with the dependencies. liblas-dev is dependent on libcurl4-gnutls-dev. But that package and libcurl4-openssl-dev seems to be mutually exclusive, they can't be installed together because the .so files are named the same. The problem is that the latter is a dependency of ros groovy. This means that there will be a conflict when trying to install liblas-dev with apt-get. Any workarounds for this?

**Comment by marc-hanheide** [comment]
Weird, never had that problem. Was all smooth on my side.

**Comment by nilsbore** [comment]
Strange, got the dependencies to install now somehow. Must have read the name wrong. Docking working like a charm now, good work!
