### ISSUE TITLE
What is the scitos_touch package?

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_apps#32]
@cdondrup is this a specific thing or the start of a more general touch interface?

**Comment by cdondrup** [comment]
I just wasn't sure on where to put nodes that are meant to be used mostly on the robots touch screen like this emergency button. If we have a common place for rqt plugins, then this can be moved there.

**Comment by hawesie** [comment]
Sounds sensible. Let's keep the scitos-only stuff here, and I will make a strands_touch package elsewhere for our strands-specific parts.
