### ISSUE TITLE
Various scripts

### ISSUE THREAD

**Issue by RaresAmbrus** [strands-project/scitos_apps#35]
Hi all,

Over the past couple of weeks we've created a couple of scripts which might be useful to others as well:
- a script that reads from a text file a number of sentences and then speaks them out in random order and at random time intervals.
- a script that monitors the odometry and sends an email (from an email address taken in as parameter) to a set of email addresses (also taken as parameter) informing that the robot is stuck.
- a script that copies a file or folder to an ftp (we are using this to remotely store data logged during runs). 

Should I merge any of these to the trunk? 

Rares

**Comment by cdondrup** [comment]
Sounds interesting. Just out of curiosity, what do you use the first script for?
Just try to find the right  repositories for these and open a pull request. I think the second one could go in here somewhere. Not sure about the other two, though.

**Comment by RaresAmbrus** [comment]
We used that once for a demo where the robot was patrolling, and every now and then it would say something like "Would you like some tea?" or "You're in my way" etc etc.

**Comment by kunzel** [comment]
It sounds as if these scripts would better fit into strands_utils? Or if they are only related to the scitos robot platform maybe create a new package called scitos_utils?

**Comment by cdondrup** [comment]
Not sure if anything ever happened but given the age of this issue, I'll close it.
