### ISSUE TITLE
Docking Calibration failed

### ISSUE THREAD

**Issue by ToMadoRe** [strands-project/scitos_apps#38]
I get the following message after running actionlib axclient.py /chargingServer and sending the goal:

Feedback:
Progress: 100
Level: 0
Message: confused by not seeing the charging station

Result:
Message: Calibration failed.

Running scitos_docking visual_charging also gives me the warning:
 [ WARN] [1381485077.489739298]: Config file not set, calibration parameters will not be loaded.

Note: I can see the "Robot Station" tag in the published RGB-topic (/head_xtion/rgb/image_color)

Does anyone know how I can fix this?

**Comment by gestom** [comment]
Ad parameters:
Try to start the charging service using the lauch file, i.e.: roslaunch scitos_docking charging.launch
The parameters should be saved to ~/.charging.yaml

Ad charging debug: 
You can try to have a look at the image published at /charging/processedimage during the calibration process.
If the three o's are modified, then the charging works properly.

**Comment by ghost** [comment]
I think we got the same error when we tried to calibrate it while it wasn't
ON the charging station.

However we pretty much always get the message calibration failed, while the
message on the bottom says succeeded. We just run with this and it seems to
be working just fine if we give the 'charge' command.

**Comment by gestom** [comment]
You should specify the file, where to save/load the calibration results (see the charging.launch). Thus, you will avoid the need of performing calibration every time you restart ROS or the robot.
If you do not specify the file, the calibration will report failure even when everything else went OK.
I will modify the charging service messages and the autonomous patroler README to reflect that.
