### ISSUE TITLE
cancelling docking action

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/scitos_apps#42]
When I try to preempt the docking 'charge' action, I get the following error (this message is continuously printed):

[ERROR] [1381856635.565067580]: To transition to a cancelled state, the goal must be in a pending, recalling, active, or preempting state, it is currently in state: 4

After the trying to preempt, 0 velocity commands keep being published in /cmd_vel

This also happens if you use the 'CANCEL GOAL' button in the rosrun actionlib axclient.py /chargingServer gui

**Comment by gestom** [comment]
Hi Bruno, the pull request from two days ago is supposed to solve that.

**Comment by bfalacerda** [comment]
ok cool, I'll give it a go then

**Comment by bfalacerda** [comment]
Everything seems to be working except that the 0 velocity commands keep being published in /cmd_vel after the preemption. It's only after a success or failure that they stop being published. 

I also forced some docking failures in simulation and it looks look it's always outputting the correct result.

**Comment by gestom** [comment]
Hehe, one argument for the mux.

**Comment by gestom** [comment]
OK, I have updated the code, that it should not publish to /cmd_vel after preemption. Could you give it a try ?

**Comment by bfalacerda** [comment]
Sure, I'll tell you something tomorrow

**Comment by bfalacerda** [comment]
works! Thanks

**Comment by gestom** [comment]
thanks for trying it out
