### ISSUE TITLE
Jenkins build failed

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/scitos_apps#43]
http://marcs-pc:8080/job/catkin_make_strands_desktop_full/ws/catkin_ws/src/scitos_apps/scitos_docking/src/testPtuClient.cpp:2:43: fatal error: move_base_msgs/MoveBaseAction.h: No such file or directory
compilation terminated.

**Comment by marc-hanheide** [comment]
@BFALacerda the jenkins build also failed today (see email). The key message is 

```
/var/lib/jenkins/jobs/catkin_make_strands_desktop_full/workspace/catkin_ws/src/scitos_apps/scitos_docking/src/testPtuClient.cpp:2:43: fatal error: move_base_msgs/MoveBaseAction.h: No such file or directory
compilation terminated.
```

Has anything changed in move_base_msgs/MoveBaseAction.h. I can't see anything. @gestom, could it also be some dependency bug again?

**Comment by gestom** [comment]
Yeap, there seem to be two dependency bugs, one in scitos_docking and other in strands_hri

**Comment by gestom** [comment]
We (with cdondrup) have corrected the bugs and have opened the pull requests at strands_hri and scitos_apps.
