### ISSUE TITLE
Safe teleop

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_apps#5]
It would be great to have a teleop node that does safe movement, ie while avoiding obstacles. This is essential for reliable web control at least.

**Comment by marc-hanheide** [comment]
Is there an easy way to combine velocity control (what the joystick does) with obstacle avoidance using position control (what move_base provides)? Of course, one could set local position goals ("carrots") using the joystick. But I know form experience that this shouldn't happen at higher frequencies (e.g. >1Hz), because then move_base freezes up.

**Comment by hawesie** [comment]
Could we also do something simpler, e.g. passing the joystick velocity through some function based on sensor reading so it becomes "harder" to push the robot into obstacles? Add in an auto stop based on the sensors too, and this might do it.

**Comment by marc-hanheide** [comment]
Sure, we could simply use some potential field approach with vectors pointing away from obstacles (limited range, vector's magnitudes should be reciprocal to distance of obstacle.) and integrate them with the velocity vector obtained from the joystick. That would usually make no difference, but only in the presences of obstacles the robot would be "guided away"...

**Comment by kunzel** [comment]
I know that the Bosch group was working on shared autonomy during the PR2 Beta program. Maybe they have some results/code in that direction. I'll try to find out. I also found this after a quick google search: http://ros.org/wiki/cob_collision_velocity_filter

**Comment by marc-hanheide** [comment]
That looks very much like something we'd need, indeed... although it only
seems to slow down and not actively navigate around. But for safety that's
enough.

On 14 July 2013 20:49, Lars Kunze notifications@github.com wrote:

> I know that the Bosch group was working on shared autonomy during the PR2
> Beta program. Maybe they have some results/code in that direction. I'll try
> to find out. I also found this after a quick google search:
> http://ros.org/wiki/cob_collision_velocity_filter
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/strands-project/scitos_apps/issues/5#issuecomment-20942488
> .

## 

---

Dr. Marc Hanheide
Senior Lecturer in Computer Science
University of Lincoln
Brayford Pool
Lincoln, LN6 7TS
Phone: +44 1522 88 6966
EMail: marc@hanheide.net
Web: http://www.hanheide.net
skype: mah99de

**Comment by hawesie** [comment]
Yeah, that looks cool.

**Comment by kunzel** [comment]
Meanwhile, I also received an answer from the Bosch guys. They have also a package that might help: http://sourceforge.net/p/bosch-ros-pkg/code/1685/tree/trunk/stacks/bosch_shared_autonomy/safe_teleop_base/

**Comment by hawesie** [comment]
Is there any documentation for the Bosch node? @marc-hanheide can one of your interns test these?

**Comment by marc-hanheide** [comment]
They are quite busy with other stuff this week. Don't expect anything soon.
If anybody else has got some time to try it, please go ahead and tell here.

**Comment by cdondrup** [comment]
Are there any news on this? Do we still need this? Is anyone but us supposed to teleop the robot? @marc-hanheide @hawesie

**Comment by marc-hanheide** [comment]
I didn't miss it so far ...

**Comment by hawesie** [comment]
I still think this is a desirable feature, but just not for expert users near the robot. If security guards are ever remote controlling bob then this will need to be reopened.
