### ISSUE TITLE
Error in roslaunch scitos_teleop

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/scitos_apps#51]
Hi,

Leeds robot seems to be working finally, I did the whole setup from the beginning and now am facing this issue !

I get the following error when I start the joystick
ERROR: cannot launch node of type [joy/joy_node]: joy

any advice !
# 

strands@strands-Mi956:~$ roslaunch scitos_teleop teleop_joystick.launch js:=/dev/input/js1
... logging to /home/strands/.ros/log/3547f00c-51e1-11e3-80fe-843a4b7f0ffc/roslaunch-strands-Mi956-12607.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://strands-Mi956:43396/
# SUMMARY

PARAMETERS
- /joystick/autorepeat_rate
- /joystick/dev
- /rosdistro
- /rosversion
- /teleop_base/scale_angular
- /teleop_base/scale_linear

NODES
  /
    joystick (joy/joy_node)
    teleop_base (scitos_teleop/teleop_base)
    teleop_head (scitos_teleop/head_teleop.py)
    teleop_joystick (scitos_teleop/rumble_control)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [joy/joy_node]: joy
ROS path [0]=/opt/ros/groovy/share/ros
ROS path [1]=/opt/strands/strands_catkin_ws/src
ROS path [2]=/opt/ros/groovy/share
ROS path [3]=/opt/ros/groovy/stacks
process[teleop_joystick-2]: started with pid [12625]
process[teleop_base-3]: started with pid [12638]
process[teleop_head-4]: started with pid [12654]
# 

Muhannad

**Comment by hawesie** [comment]
Is that all the output? I did have some problems with the joystick device not being readable (fix: `sudo chmod a+r /dev/input/js1`) and also the joystick device switching between js0 and js1, but both give different error output.

**Comment by OMARI1988** [comment]
I tried it and it didn't work, still same error.

strands@strands-Mi956:~$ roslaunch scitos_teleop teleop_joystick.launch
js:=/dev/input/js1
... logging to
/home/strands/.ros/log/7cc2ddde-51e6-11e3-85c1-843a4b7f0ffc/roslaunch-strands-Mi956-15234.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://strands-Mi956:55938/

# SUMMARY

PARAMETERS
- /joystick/autorepeat_rate
- /joystick/dev
- /rosdistro
- /rosversion
- /teleop_base/scale_angular
- /teleop_base/scale_linear

NODES
  /
    joystick (joy/joy_node)
    teleop_base (scitos_teleop/teleop_base)
    teleop_head (scitos_teleop/head_teleop.py)
    teleop_joystick (scitos_teleop/rumble_control)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [joy/joy_node]: joy
ROS path [0]=/opt/ros/groovy/share/ros
ROS path [1]=/opt/strands/strands_catkin_ws/src
ROS path [2]=/opt/ros/groovy/share
ROS path [3]=/opt/ros/groovy/stacks
ROS path [4]=/opt/strands/strands_catkin_ws
process[teleop_joystick-2]: started with pid [15252]
process[teleop_base-3]: started with pid [15265]
process[teleop_head-4]: started with pid [15281]

**Comment by bfalacerda** [comment]
I think you need to install joy. Follow 1.1 here:

http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick

Then, follow 1.2 to find where the joystick device is (typically /dev/input/js0 or /dev/input/js1), and run 

```
$  roslaunch scitos_teleop teleop_joystick.launch js:=/dev/input/jsX 
```

where X is where you found the joystick

**Comment by RaresAmbrus** [comment]
You can use the following on the command line to check whether your joystick is working (where X is the device number, probably 0 or 1):

```
jstest /dev/ttyUSBX
```

**Comment by OMARI1988** [comment]
I get the following after the test

strands@strands-Mi956:~$ jstest /dev/ttyUSB0
Driver version is 0.8.0.
jstest is not fully compatible with your kernel. Unable to retrieve button
map!
Joystick (Unknown) has 2 axes and 2 buttons.
Testing ... (interrupt to exit)
Axes: X:3407924 Y:3407925 Buttons: A:off B:off B:off
jstest: error reading: Inappropriate ioctl for device
strands@strands-Mi956:~$

**Comment by OMARI1988** [comment]
and for USB1 I get this

strands@strands-Mi956:~$ jstest /dev/ttyUSB1
Driver version is 0.8.0.
jstest is not fully compatible with your kernel. Unable to retrieve button
map!
Joystick (Unknown) has 2 axes and 2 buttons.
Testing ... (interrupt to exit)

but I can see it on jstest-gtk ! its js0

**Comment by OMARI1988** [comment]
but when I test with js0 it works

jstest --normal /dev/input/js0

it updates the inputs when I press any button.

**Comment by RaresAmbrus** [comment]
Sorry, it was /dev/input/js0, not /dev/ttyUSB0. It seems like your joystick is working fine, there's no reason why the ros node wouldn't work; have you followed the tutorial from Bruno's link?

**Comment by OMARI1988** [comment]
can you send me the link please ?

**Comment by OMARI1988** [comment]
http://www.omgubuntu.co.uk/2013/07/dealing-with-xbox-controllers-in-ubuntu

This thing fixed the X mode but I have to keep this command running

sudo xboxdrv --silent

I tried the permanent solution suggested and it gives no such path or
directory ! any ideas

Muhannad

**Comment by OMARI1988** [comment]
LUCIE is moving around using this command to set the driver for the
joystick (its working and if I find a better solution I will add it)

sudo xboxdrv --silent

And the previous error was there because ROS joy was not installed.

I will close this.
