### ISSUE TITLE
scitos_docking missing scitos_apps_msgs/ChargingAction.h

### ISSUE THREAD

**Issue by OMARI1988** [strands-project/scitos_apps#52]
Hi,

I can't build scitos_docking, it gives the following error !

/opt/strands/strands_catkin_ws/src/scitos_docking/src/CPtuClient.h:11:45: fatal error: scitos_apps_msgs/ChargingAction.h: No such file or directory
compilation terminated.

what I did yesterday is I removed scitos_docking folder from the src folder and the build succeeded, Lucie was working, I could build maps, save waypoints and move it around with the joystick.

Now I want to start the autonomous patrolling and I need the docking.
# 

strands@strands-Mi956:/opt/strands/strands_catkin_ws$ catkin_make
Base path: /opt/strands/strands_catkin_ws
Source space: /opt/strands/strands_catkin_ws/src
Build space: /opt/strands/strands_catkin_ws/build
Devel space: /opt/strands/strands_catkin_ws/devel
Install space: /opt/strands/strands_catkin_ws/install
#### 
#### 
#### 
#### 

[  0%] Built target amcl_gencfg
[  0%] [  1%] Built target amcl_pf
Built target amcl_map
[  1%] Built target std_msgs_generate_messages_lisp
[  1%] [  1%] Built target std_msgs_generate_messages_cpp
Built target std_msgs_generate_messages_py
[  1%] Built target flir_pantilt_d46
[  2%] Built target fake_localization
[  2%] [  2%] [  2%] Built target actionlib_msgs_generate_messages_py
Built target actionlib_msgs_generate_messages_cpp
Built target sensor_msgs_generate_messages_py
[  2%] Built target sensor_msgs_generate_messages_cpp
[  2%] Built target actionlib_msgs_generate_messages_lisp
[  2%] [  2%] Built target ptu_d46
Built target sensor_msgs_generate_messages_lisp
[  3%] Built target image_blurrer_node
[  3%] [  3%] Built target libav_compressor_generate_messages_py
[  3%] Built target libav_compressor_generate_messages_cpp
Built target libav_compressor_generate_messages_lisp
[  3%] Built target image_loader
[  4%] [  4%] Built target map_saver
Built target gtest
[  4%] Built target geometry_msgs_generate_messages_cpp
[  4%] Built target geometry_msgs_generate_messages_py
[  4%] Built target mjpeg_server
[  4%] Built target geometry_msgs_generate_messages_lisp
[  4%] Built target roscpp_generate_messages_cpp
[  4%] [  4%] Built target roscpp_generate_messages_py
Built target roscpp_generate_messages_lisp
[  4%] Built target rosgraph_msgs_generate_messages_py
[  4%] Built target rosgraph_msgs_generate_messages_cpp
[  4%] [  4%] Built target openni_saver_generate_messages_lisp
[  4%] Built target openni_saver_generate_messages_py
Built target rosgraph_msgs_generate_messages_lisp
[  4%] Built target openni_saver_generate_messages_cpp
[  4%] Built target robot_pose_ekf_generate_messages_cpp
[  4%] Built target robot_pose_ekf_generate_messages_lisp
[  4%] Built target robot_pose_ekf_generate_messages_py
[  5%] Built target openni_wrapper_lib
[  5%] Built target test_robot_pose_ekf_zero_covariance
[  5%] Built target test_robot_pose_ekf
[  6%] Built target ros_mary_tts_generate_messages_py
[  7%] Built target robot_state_chain_publisher
[  8%] Built target ros_mary_tts_generate_messages_cpp
[  9%] Built target ros_mary_tts_generate_messages_lisp
[ 12%] Built target rosbridge_library_generate_messages_py
[ 14%] Built target rosbridge_library_generate_messages_cpp
[ 16%] Built target rosbridge_library_generate_messages_lisp
[ 19%] Built target rosapi_generate_messages_cpp
[ 22%] Built target rosapi_generate_messages_lisp
[ 26%] Built target rosapi_generate_messages_py
[ 27%] Built target noise_approximate_voxel_grid
[ 27%] Built target noise_voxel_grid
[ 27%] [ 27%] [ 28%] Built target remove_edges_cloud
Built target synthesize_wall_cloud
Built target scitos_apps_msgs_generate_messages_py
[ 29%] Built target scitos_apps_msgs_generate_messages_lisp
[ 30%] Built target scitos_apps_msgs_generate_messages_cpp
[ 31%] [ 32%] Built target scitos_msgs_generate_messages_lisp
[ 33%] Built target scitos_msgs_generate_messages_py
Built target scitos_msgs_generate_messages_cpp
[ 33%] [ 35%] [ 35%] Built target scitos_ptu_generate_messages_py
Built target scitos_ptu_generate_messages_cpp
Generating dynamic reconfigure files from cfg/ChargerParameters.cfg: /opt/strands/strands_catkin_ws/devel/include/scitos_mira/ChargerParametersConfig.h /opt/strands/strands_catkin_ws/devel/lib/python2.7/dist-packages/scitos_mira/cfg/ChargerParametersConfig.py
[ 36%] [ 37%] Built target scitos_ptu_generate_messages_lisp
Generating dynamic reconfigure files from cfg/EBCParameters.cfg: /opt/strands/strands_catkin_ws/devel/include/scitos_mira/EBCParametersConfig.h /opt/strands/strands_catkin_ws/devel/lib/python2.7/dist-packages/scitos_mira/cfg/EBCParametersConfig.py
[ 38%] Built target scitos_ptu_sweep_generate_messages_lisp
[ 39%] Built target scitos_ptu_sweep_generate_messages_py
[ 39%] Generating dynamic reconfigure files from cfg/DisplayParameters.cfg: /opt/strands/strands_catkin_ws/devel/include/scitos_mira/DisplayParametersConfig.h /opt/strands/strands_catkin_ws/devel/lib/python2.7/dist-packages/scitos_mira/cfg/DisplayParametersConfig.py
[ 40%] Built target scitos_ptu_sweep_generate_messages_cpp
[ 40%] Built target transform_pc2
[ 40%] Built target teleop_base
[ 40%] Built target sick300_driver
[ 41%] Built target smach_msgs_generate_messages_py
[ 41%] Built target smach_msgs_generate_messages_cpp
[ 41%] Built target smach_msgs_generate_messages_lisp
[ 42%] Built target strands_datacentre_generate_messages_py
[ 42%] Built target strands_datacentre_generate_messages_lisp
[ 43%] Built target strands_datacentre_generate_messages_cpp
[ 43%] Built target calibrate_chest
[ 43%] Built target chest_calibration_publisher
[ 43%] Built target CLightClient
Generating reconfiguration files for ChargerParameters in scitos_mira
[ 44%] Built target CTimer
Generating reconfiguration files for EBCParameters in scitos_mira
[ 44%] Built target CCircleDetect
Generating reconfiguration files for DisplayParameters in scitos_mira
[ 44%] Built target CDump
[ 44%] Building CXX object scitos_docking/CMakeFiles/CPtuClient.dir/src/CPtuClient.cpp.o
[ 44%] Built target CRawImage
[ 44%] Built target scitos_mira_gencfg
[ 44%] Built target CTransformation
[ 45%] [ 45%] [ 45%] Built target costmap_2d_gencfg
Built target move_base_gencfg
Built target costmap_2d_generate_messages_cpp
[ 45%] Built target strands_diagnostics_generate_messages_lisp
[ 45%] Built target voxel_grid
[ 45%] Built target strands_diagnostics_generate_messages_cpp
[ 45%] Built target strands_diagnostics_generate_messages_py
[ 47%] [ 47%] Built target strands_gazing_generate_messages_cpp
Built target strands_gazing_generate_messages_lisp
[ 48%] [ 48%] Built target strands_gazing_generate_messages_py
[ 50%] Built target strands_perception_people_msgs_generate_messages_lisp
Built target strands_perception_people_msgs_generate_messages_cpp
[ 51%] Built target strands_human_aware_velocity_generate_messages_py
[ 52%] Built target strands_human_aware_velocity_generate_messages_lisp
[ 53%] Built target strands_perception_people_msgs_generate_messages_py
[ 54%] [ 54%] Built target strands_tweets_generate_messages_py
Built target strands_human_aware_velocity_generate_messages_cpp
[ 55%] Built target strands_tweets_generate_messages_cpp
[ 56%] Built target strands_visualise_speech_generate_messages_py
[ 57%] [ 57%] Built target strands_visualise_speech_generate_messages_lisp
Built target strands_tweets_generate_messages_lisp
[ 58%] Built target strands_visualise_speech_generate_messages_cpp
[ 59%] [ 60%] Built target strands_hri_utils_generate_messages_lisp
Built target strands_hri_utils_generate_messages_py
[ 61%] Built target strands_hri_utils_generate_messages_cpp
[ 62%] [ 62%] Built target strands_webserver_generate_messages_lisp
Built target strands_webserver_generate_messages_cpp
[ 63%] Built target strands_webserver_generate_messages_py
[ 63%] [ 63%] Built target usbreset
Built target folder_player
[ 63%] Built target show_depth_node
[ 63%] Built target show_ir_node
[ 63%] Built target object_segmentation_node
[ 63%] [ 63%] Built target show_rgb_node
Built target voxel_grid_sample
[ 63%] Built target costmap_2d_generate_messages_lisp
[ 63%] Built target base_local_planner_gencfg
[ 63%] Built target costmap_2d_generate_messages_py
[ 63%] Built target base_local_planner_generate_messages_lisp
[ 63%] Built target base_local_planner_generate_messages_cpp
[ 63%] Built target base_local_planner_generate_messages_py
[ 63%] Built target dwa_local_planner_gencfg
[ 63%] Built target nav_msgs_generate_messages_lisp
[ 63%] Built target nav_msgs_generate_messages_py
[ 63%] Built target nav_msgs_generate_messages_cpp
[ 63%] Built target waypoint_patroller_gencfg
[ 64%] Built target amcl_sensors
[ 65%] Built target ap_msgs_generate_messages_lisp
[ 66%] Built target ap_msgs_generate_messages_cpp
[ 67%] Built target ap_msgs_generate_messages_py
[ 70%] Built target flir_pantilt_d46_generate_messages_py
[ 72%] Built target flir_pantilt_d46_generate_messages_cpp
[ 72%] [ 76%] Built target flir_pantilt_d46_generate_messages_lisp
Built target libav_compressor_generate_messages
[ 76%] Built target map_server
[ 77%] In file included from /opt/strands/strands_catkin_ws/src/scitos_docking/src/CPtuClient.cpp:1:0:
/opt/strands/strands_catkin_ws/src/scitos_docking/src/CPtuClient.h:11:45: fatal error: scitos_apps_msgs/ChargingAction.h: No such file or directory
compilation terminated.
Built target move_base_msgs_generate_messages_py
[ 78%] Built target rtest
[ 79%] Built target move_base_msgs_generate_messages_lisp
[ 80%] [ 80%] [ 81%] Built target nav_goals_msgs_generate_messages_cpp
Built target move_base_msgs_generate_messages_cpp
Built target nav_goals_msgs_generate_messages_lisp
[ 81%] Built target openni_saver_generate_messages
[ 81%] Built target nav_goals_msgs_generate_messages_py
[ 81%] Built target openni_image_saver
[ 81%] Built target robot_pose_ekf_gencpp
[ 81%] Built target robot_pose_ekf_generate_messages
[ 81%] Built target openni_wrapper
[ 81%] Built target ros_mary_tts_generate_messages
[ 81%] Built target state_chain_publisher
[ 81%] Built target rosbridge_library_generate_messages
[ 81%] Built target rosapi_generate_messages
[ 81%] Built target scitos_apps_msgs_generate_messages
[ 81%] [ 81%] Built target subsample_cloud
Built target ap_msgs_gencpp
[ 81%] Built target scitos_msgs_generate_messages
[ 81%] [ 81%] Built target scitos_ptu_generate_messages
Built target scitos_msgs_gencpp
[ 81%] Built target scitos_ptu_sweep_generate_messages
[ 81%] Built target smach_msgs_generate_messages
[ 81%] Scanning dependencies of target CChargingActions
Built target strands_datacentre_generate_messages
[ 81%] Building CXX object scitos_docking/CMakeFiles/CChargingClient.dir/src/CChargingClient.cpp.o
[ 81%] Built target costmap_2d_gencpp
[ 81%] Built target move_base_msgs_gencpp
Scanning dependencies of target visual_charging_client
[ 81%] Building CXX object scitos_docking/CMakeFiles/visual_charging_client.dir/src/dockingClient.cpp.o
[ 81%] Building CXX object scitos_docking/CMakeFiles/CChargingActions.dir/src/CChargingActions.cpp.o
In file included from /opt/strands/strands_catkin_ws/src/scitos_docking/src/CChargingClient.cpp:1:0:
/opt/strands/strands_catkin_ws/src/scitos_docking/src/CChargingClient.h:11:45: fatal error: scitos_apps_msgs/ChargingAction.h: No such file or directory
compilation terminated.
/opt/strands/strands_catkin_ws/src/scitos_docking/src/dockingClient.cpp:2:45: fatal error: scitos_apps_msgs/ChargingAction.h: No such file or directory
compilation terminated.
make[2]: **\* [scitos_docking/CMakeFiles/CPtuClient.dir/src/CPtuClient.cpp.o] Error 1
make[1]: **\* [scitos_docking/CMakeFiles/CPtuClient.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make[2]: **\* [scitos_docking/CMakeFiles/visual_charging_client.dir/src/dockingClient.cpp.o] Error 1
make[1]: **\* [scitos_docking/CMakeFiles/visual_charging_client.dir/all] Error 2
make[2]: **\* [scitos_docking/CMakeFiles/CChargingClient.dir/src/CChargingClient.cpp.o] Error 1
make[1]: **\* [scitos_docking/CMakeFiles/CChargingClient.dir/all] Error 2
Linking CXX shared library /opt/strands/strands_catkin_ws/devel/lib/libCChargingActions.so
[ 81%] Built target CChargingActions
make: **\* [all] Error 2
Invoking "make" failed

**Comment by gestom** [comment]
Hi, can you check if the file exist on your system?

**Comment by OMARI1988** [comment]
No its not there

**Comment by gestom** [comment]
can you sent me a list of the files in your scitos_apps_msgs/action directory?

**Comment by OMARI1988** [comment]
I have two files there

strands@strands-Mi956:/opt/strands/strands_catkin_ws/src/scitos_apps/scitos_apps_msgs/action$
ls
Charging.action  RampClimbing.action

**Comment by OMARI1988** [comment]
and on github that file is not there anywhere in scitos_apps_msgs

https://github.com/hawesie/scitos_apps/tree/master/scitos_apps_msgs

**Comment by OMARI1988** [comment]
Fixed.

in  /strands/strands_catkin_ws/src/scitos_apps/scitos_apps_msgs

I commented the RampClimbing.action in the CMakeLists.txt line 11 ==>
Charging.actions was build correctly !

add_action_files(
        DIRECTORY action
        FILES Charging.action
        # FILES RampClimbing.action

)

I will close this
