### ISSUE TITLE
[scitos_docking] depends on datacentre messages

### ISSUE THREAD

**Issue by cburbridge** [strands-project/scitos_apps#62]
Sometimes scitos_docking won't build as it is trying to be built before the messages have finished being generated for the datacentre:
#### 

[  0%] [  0%] [  0%] Built target actionlib_msgs_generate_messages_cpp
Built target std_msgs_generate_messages_py
Built target actionlib_msgs_generate_messages_py
[  0%] [  0%] [  0%] Built target actionlib_msgs_generate_messages_lisp
Built target std_msgs_generate_messages_cpp
Built target std_msgs_generate_messages_lisp
[  0%] [  0%] Built target sensor_msgs_generate_messages_py
Built target sensor_msgs_generate_messages_lisp
[  0%] [  0%] Generating Python from MSG smach_msgs/SmachContainerStatus
Building CXX object scitos_apps/scitos_teleop/CMakeFiles/teleop_base.dir/src/base_teleop.cpp.o
[  0%] [  0%] Built target sensor_msgs_generate_messages_cpp
[  1%] [  1%] [  1%] Building CXX object scitos_common/calibrate_chest/CMakeFiles/chest_calibration_publisher.dir/src/chest_calibration_publisher.cpp.o
Building CXX object scitos_apps/scitos_docking/CMakeFiles/CTimer.dir/src/CTimer.cpp.o
Building CXX object scitos_apps/scitos_docking/CMakeFiles/CLightClient.dir/src/CLightClient.cpp.o
Generating Python code from SRV strands_datacentre/GetParam
[  1%] [  2%] Building CXX object scitos_apps/scitos_docking/CMakeFiles/CDump.dir/src/CDump.cpp.o
Building CXX object scitos_apps/scitos_docking/CMakeFiles/CCircleDetect.dir/src/CCircleDetect.cpp.o
Linking CXX shared library /home/chris/hydro-test/devel/lib/libCTimer.so
[  3%] Generating Python from MSG smach_msgs/SmachContainerStructure
[  4%] Generating Python code from SRV strands_datacentre/MongoUpdate
[  4%] Built target CTimer
Linking CXX shared library /home/chris/hydro-test/devel/lib/libCDump.so
[  5%] Building CXX object scitos_apps/scitos_docking/CMakeFiles/CRawImage.dir/src/CRawImage.cpp.o
Linking CXX shared library /home/chris/hydro-test/devel/lib/libCCircleDetect.so
[  5%] [  5%] Built target CDump
Generating Python from MSG smach_msgs/SmachContainerInitialStatusCmd
[  5%] Generating Python code from SRV strands_datacentre/MongoFind
[  5%] Scanning dependencies of target CTransformation
Built target CCircleDetect
[  6%] Generating Python from MSG strands_diagnostics/DiagnosticMessage
Linking CXX shared library /home/chris/hydro-test/devel/lib/libCRawImage.so
[  7%] [  8%] Generating Python msg **init**.py for smach_msgs
Building CXX object scitos_apps/scitos_docking/CMakeFiles/CTransformation.dir/src/CTransformation.cpp.o
[  8%] Built target CRawImage
[  8%] Generating Python msg **init**.py for strands_diagnostics
[  9%] [  9%] Generating Python code from SRV strands_datacentre/SetParam
Generating Lisp code from strands_diagnostics/DiagnosticMessage.msg
[  9%] Built target smach_msgs_generate_messages_py
[  9%] Generating Python code from SRV strands_datacentre/MongoInsert
[  9%] Built target strands_diagnostics_generate_messages_py
[  9%] Built target strands_diagnostics_generate_messages_lisp
[ 10%] [ 10%] Generating C++ code from strands_diagnostics/DiagnosticMessage.msg
Built target geometry_msgs_generate_messages_lisp
[ 10%] Built target geometry_msgs_generate_messages_py
[ 10%] Built target geometry_msgs_generate_messages_cpp
[ 11%] [ 12%] Generating Python srv **init**.py for strands_datacentre
Generating Python from MSG scitos_apps_msgs/ChargingAction
[ 13%] Generating C++ code from scitos_apps_msgs/ChargingAction.msg
[ 13%] Built target strands_datacentre_generate_messages_py
[ 13%] Generating C++ code from scitos_apps_msgs/ChargingActionResult.msg
[ 13%] Generating Python from MSG scitos_apps_msgs/ChargingActionResult
[ 13%] Built target strands_diagnostics_generate_messages_cpp
[ 14%] Generating C++ code from scitos_apps_msgs/ChargingFeedback.msg
In file included from /home/chris/hydro-test/src/scitos_apps/scitos_docking/src/CTransformation.cpp:1:0:
/home/chris/hydro-test/src/scitos_apps/scitos_docking/src/CTransformation.h:16:41: fatal error: strands_datacentre/SetParam.h: No such file or directory
compilation terminated.
[ 15%] Generating Python from MSG scitos_apps_msgs/ChargingFeedback
[ 16%] Generating Python from MSG scitos_apps_msgs/RampClimbingGoal
[ 16%] [ 17%] Generating Python from MSG scitos_apps_msgs/RampClimbingAction
Generating Lisp code from scitos_apps_msgs/ChargingAction.msg
[ 18%] [ 18%] Generating Python from MSG scitos_apps_msgs/RampClimbingResult
Generating C++ code from scitos_apps_msgs/RampClimbingGoal.msg
[ 18%] [ 18%] Generating Python from MSG scitos_apps_msgs/RampClimbingActionResult
Generating Lisp code from scitos_apps_msgs/ChargingActionResult.msg
[ 19%] Generating Python from MSG scitos_apps_msgs/action_buttons
[ 20%] Generating Lisp code from scitos_apps_msgs/ChargingFeedback.msg
[ 20%] Generating Python from MSG scitos_apps_msgs/RampClimbingActionGoal
[ 20%] Generating C++ code from scitos_msgs/ChargerStatus.msg
[ 20%] [ 21%] [ 22%] Generating Lisp code from scitos_apps_msgs/RampClimbingGoal.msg
Generating Python from MSG scitos_apps_msgs/ChargingActionFeedback
Generating C++ code from scitos_apps_msgs/RampClimbingAction.msg
[ 23%] Generating Python from MSG scitos_apps_msgs/ChargingActionGoal
[ 24%] Generating Lisp code from scitos_apps_msgs/RampClimbingAction.msg
[ 24%] [ 25%] Generating Python from MSG scitos_apps_msgs/RampClimbingFeedback
Generating C++ code from scitos_msgs/HeadLightState.msg
[ 25%] Generating C++ code from scitos_apps_msgs/RampClimbingResult.msg
[ 26%] Generating Lisp code from scitos_apps_msgs/RampClimbingResult.msg
[ 27%] Generating Python from MSG scitos_apps_msgs/RampClimbingActionFeedback
[ 27%] Generating Lisp code from scitos_apps_msgs/RampClimbingActionResult.msg
[ 27%] Generating Python from MSG scitos_apps_msgs/ChargingGoal
[ 27%] Generating C++ code from scitos_msgs/BatteryState.msg
[ 28%] Generating Lisp code from scitos_apps_msgs/action_buttons.msg
[ 29%] Generating Python from MSG scitos_apps_msgs/ChargingResult
[ 30%] Generating C++ code from scitos_apps_msgs/RampClimbingActionResult.msg
[ 30%] Generating Lisp code from scitos_apps_msgs/RampClimbingActionGoal.msg
[ 30%] Generating Python code from SRV scitos_apps_msgs/Charging
[ 31%] Generating C++ code from scitos_msgs/MotorStatus.msg
[ 33%] [ 33%] Generating Lisp code from scitos_apps_msgs/ChargingActionFeedback.msg
Generating Python msg **init**.py for scitos_apps_msgs
[ 34%] [ 35%] Generating Python srv **init**.py for scitos_apps_msgs
Generating C++ code from scitos_apps_msgs/action_buttons.msg
[ 35%] make[2]: **\* [scitos_apps/scitos_docking/CMakeFiles/CTransformation.dir/src/CTransformation.cpp.o] Error 1
make[1]: **\* [scitos_apps/scitos_docking/CMakeFiles/CTransformation.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
Generating Lisp code from scitos_apps_msgs/ChargingActionGoal.msg
[ 36%] Generating Lisp code from scitos_apps_msgs/RampClimbingFeedback.msg
[ 36%] Built target scitos_apps_msgs_generate_messages_py
[ 36%] Generating C++ code from scitos_msgs/EnableMotors.srv
[ 37%] Generating Lisp code from scitos_apps_msgs/RampClimbingActionFeedback.msg
[ 37%] [ 37%] Generating C++ code from scitos_apps_msgs/RampClimbingActionGoal.msg
Generating Lisp code from scitos_apps_msgs/ChargingGoal.msg
Linking CXX executable /home/chris/hydro-test/devel/lib/calibrate_chest/chest_calibration_publisher
[ 38%] Generating Lisp code from scitos_apps_msgs/ChargingResult.msg
[ 39%] Generating C++ code from scitos_msgs/EmergencyStop.srv
[ 39%] [ 40%] Generating Lisp code from scitos_apps_msgs/Charging.srv
Generating C++ code from scitos_msgs/ResetOdometry.srv
[ 41%] Generating C++ code from scitos_apps_msgs/ChargingActionFeedback.msg
[ 41%] Built target scitos_apps_msgs_generate_messages_lisp
[ 41%] Generating C++ code from scitos_msgs/ResetMotorStop.srv
Linking CXX executable /home/chris/hydro-test/devel/lib/scitos_teleop/teleop_base
[ 41%] Generating C++ code from scitos_apps_msgs/ChargingActionGoal.msg
[ 42%] Linking CXX shared library /home/chris/hydro-test/devel/lib/libCLightClient.so
Generating C++ code from scitos_apps_msgs/RampClimbingFeedback.msg
[ 42%] Generating C++ code from scitos_apps_msgs/RampClimbingActionFeedback.msg
[ 42%] [ 42%] Built target CLightClient
Built target teleop_base
[ 44%] [ 44%] [ 44%] Generating C++ code from scitos_apps_msgs/ChargingResult.msg
Generating C++ code from scitos_apps_msgs/ChargingGoal.msg
Generating C++ code from scitos_apps_msgs/Charging.srv
[ 44%] Built target scitos_msgs_generate_messages_cpp
[ 44%] Built target chest_calibration_publisher
[ 44%] Built target scitos_apps_msgs_generate_messages_cpp
make: **\* [all] Error 2
Invoking "make" failed

**Comment by cdondrup** [comment]
Due to the release preparations everything is using the `${catkin_EXPORTED_TARGETS}` macro in the dependencies. Therefore this shouldn't happen any more.
